{% set python_min = '3.10' %}
{% set name = "fastapi-oidc" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aeb31a44759f320e809f707d315fee2ec91a878e7d16221a1b2a40b2b424fd85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }},<4.0
    - cachetools >=4.1.1
    - fastapi >=0.61.0
    - pydantic >=2.0.0
    - python-jose >=3.2.0
    - requests >=2.24.0

test:
  imports:
    - fastapi_oidc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/HarryMWinters/fastapi-oidc
  summary: A simple library for parsing and verifying externally issued OIDC ID tokens in fastapi.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dangercrow
